=== jiteshh-10/Java-Full-Stack-Milestone-Projects/WiproJavaFSD/src/TM13XML/MobileShowroom/mobiles.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="MobileSales">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Mobile" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="Mobile">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ModelID" type="xs:integer"/>
                <xs:element name="Brand" type="xs:string"/>
                <xs:element name="Price" type="xs:integer"/>
                <xs:element name="Color" type="xs:string"/>
                <xs:element name="SIMSize">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="Normal"/>
                            <xs:enumeration value="Micro"/>
                            <xs:enumeration value="Nano"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="Memory" type="xs:string"/>
                <xs:element name="Camera" type="xs:string"/>
                <xs:element name="TouchScreen" type="xs:string"/>
                <xs:element name="NoSold" type="xs:integer"/>
                <xs:element name="storeName">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="store1"/>
                            <xs:enumeration value="store2"/>
                            <xs:enumeration value="store3"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== jiteshh-10/Java-Full-Stack-Milestone-Projects/WiproJavaFSD/src/TM13XML/MobileShowroom/mobiles.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="mobiles.xsl"?>

<MobileSales xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="mobiles.xsd">
    <Mobile>
        <ModelID>1234</ModelID>
        <Brand>Motorola</Brand>
        <Price>1000</Price>
        <Color>Black</Color>
        <SIMSize>Micro</SIMSize>
        <Memory>8GB</Memory>
        <Camera>Yes</Camera>
        <TouchScreen>Yes</TouchScreen>
        <NoSold>11</NoSold>
        <storeName>store1</storeName>
    </Mobile>
    <Mobile>
        <ModelID>3452</ModelID>
        <Brand>Micromax</Brand>
        <Price>7000</Price>
        <Color>Black</Color>
        <SIMSize>Micro</SIMSize>
        <Memory>8GB</Memory>
        <Camera>Yes</Camera>
        <TouchScreen>Yes</TouchScreen>
        <NoSold>6</NoSold>
        <storeName>store1</storeName>
    </Mobile>
    <Mobile>
        <ModelID>6878</ModelID>
        <Brand>Lenovo</Brand>
        <Price>6000</Price>
        <Color>White</Color>
        <SIMSize>Nano</SIMSize>
        <Memory>4GB</Memory>
        <Camera>Yes</Camera>
        <TouchScreen>Yes</TouchScreen>
        <NoSold>8</NoSold>
        <storeName>store1</storeName>
    </Mobile>
    <Mobile>
        <ModelID>1284</ModelID>
        <Brand>Motorola</Brand>
        <Price>4000</Price>
        <Color>Black</Color>
        <SIMSize>Micro</SIMSize>
        <Memory>8GB</Memory>
        <Camera>Yes</Camera>
        <TouchScreen>Yes</TouchScreen>
        <NoSold>5</NoSold>
        <storeName>store2</storeName>
    </Mobile>
    <Mobile>
        <ModelID>3452</ModelID>
        <Brand>Micromax</Brand>
        <Price>7000</Price>
        <Color>Black</Color>
        <SIMSize>Micro</SIMSize>
        <Memory>8GB</Memory>
        <Camera>Yes</Camera>
        <TouchScreen>Yes</TouchScreen>
        <NoSold>17</NoSold>
        <storeName>store2</storeName>
    </Mobile>
    <Mobile>
        <ModelID>1234</ModelID>
        <Brand>Motorola</Brand>
        <Price>4000</Price>
        <Color>Black</Color>
        <SIMSize>Micro</SIMSize>
        <Memory>8GB</Memory>
        <Camera>Yes</Camera>
        <TouchScreen>Yes</TouchScreen>
        <NoSold>7</NoSold>
        <storeName>store3</storeName>
    </Mobile>
    <Mobile>
        <ModelID>6878</ModelID>
        <Brand>Lenovo</Brand>
        <Price>6000</Price>
        <Color>White</Color>
        <SIMSize>Nano</SIMSize>
        <Memory>4GB</Memory>
        <Camera>Yes</Camera>
        <TouchScreen>Yes</TouchScreen>
        <NoSold>3</NoSold>
        <storeName>store3</storeName>
    </Mobile>
    <Mobile>
        <ModelID>3452</ModelID>
        <Brand>Micromax</Brand>
        <Price>7000</Price>
        <Color>Black</Color>
        <SIMSize>Micro</SIMSize>
        <Memory>8GB</Memory>
        <Camera>Yes</Camera>
        <TouchScreen>Yes</TouchScreen>
        <NoSold>2</NoSold>
        <storeName>store3</storeName>
    </MobiL>
</MobileSales>
